name = input("Please Enter your name: ")
color = input("Please Enter your favorite color name: ")
age = int(input("Please Enter your age: "))
country = input("Please Enter your country name: ")
city = input("Please Enter the name of the city in which you are: ")
print("Your name is", name)
print("Your favorite color is",color)
print("You are ",age, " years old")
print("I live in ", city, ", ", country)